language: ruby
sudo: false
bundler_args: --without development
before_install: rm Gemfile.lock || true
script: bundle exec rake test
matrix:
  fast_finish: true
  include:
  - rvm: 1.9
    env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 2.1" HIERA_GEM_VERSION="~> 1.3"
  - rvm: 1.9
    env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 2.2" HIERA_GEM_VERSION="~> 1.3"
  - rvm: 2.0
    env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 2.1" HIERA_GEM_VERSION="~> 1.3"
  - rvm: 2.0
    env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 2.2" HIERA_GEM_VERSION="~> 1.3"
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 2.1" HIERA_GEM_VERSION="~> 1.3"
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="3.8.5" FACTER_GEM_VERSION="~> 2.4" HIERA_GEM_VERSION="~> 1.3" FUTURE_PARSER="yes"
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="~> 4.3" FACTER_GEM_VERSION="~> 2.4" HIERA_GEM_VERSION="~> 3.0"
notifications:
  email: false
deploy:
  provider: puppetforge
  user: powerhome
  password:
    secure: "rHMu92sJNInuh8KMkij5jW1DabnzCkxwvbgdc1X9raCwzGfPBWG0yuTbq+pjUxMxu4DNh288zX9HNUQOhOGLPnAevi5XjtknTlg4BdZ8dfC9yIODlp2jexagbbIZR+EJdS9EnW3Qsl+/fbHx7X/cIQN7cL9y5Xsb5bfeM2NMGlw="
  on:
    tags: true
    all_branches: true
    rvm: 2.1
    condition:
    - $PUPPET_GEM_VERSION = '~> 4.3'
