name    'powerhome/lumenvox'
version '0.1.0'
source 'https://github.com/powerhome/puppet-lumenvox'
author 'Justin Aiken'
license 'MIT'
summary 'Install and manage Lumenvox services'
description 'Install and manage Lumenvox services'
project_page 'https://github.com/powerhome/puppet-lumenvox'
